#  Copyright 2015 VMware, Inc.  All rights reserved.
#  SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
---
- name: Configure clustering
  ignore_errors: yes
  vra_configure:
    vra_instance: "{{vra_instance}}"
    vra_user: "{{vra_user}}"
    vra_port: "{{vra_port}}"
    vra_root_password: "{{vra_root_password}}"
    vra_cluster:
      host: "{{vra_cluster_host}}"
      user: "{{vra_cluster_user}}"
      password: "{{vra_cluster_password}}"
  register: vra_connnected
