#  Copyright 2015 VMware, Inc.  All rights reserved.
#  SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
---
- name: Configure Messaging
  ignore_errors: yes
  vra_configure:
    vra_instance: "{{vra_host_name}}"
    vra_user: "{{vra_user}}"
    vra_port: "{{vra_port}}"
    vra_root_password: "{{vra_root_password}}"
    vra_messaging:
      host: "{{vra_messaging_host}}"
      port: "{{vra_messaging_port}}"
      user: "{{vra_messaging_user}}"
      password: "{{vra_messaging_password}}"
  register: vra_connnected
