#  Copyright 2015 VMware, Inc.  All rights reserved.
#  SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
---
- name: Configure vRA SSO
  ignore_errors: yes
  configure_vra_sso:
    vra_host_name: "{{ vra_host_name }}"
    vra_root_password: "{{ vra_root_password }}"
    vra_port: "{{ vra_port }}"
    vra_sso_host: "{{ vra_sso_host }}"
    vra_sso_user: "{{ vra_sso_user }}"
    vra_sso_password: "{{ vra_sso_password }}"
    vra_sso_port: "{{ vra_sso_port }}"
    vra_license_key: "{{ vra_license_key }}"
  register: configure_vra_sso

- name: debug config std out
  debug: var=configure_vra_sso


