#  Copyright 2015 VMware, Inc.  All rights reserved.
#  SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
---
- name: Destroying existing appliance
  ignore_errors: True
  vsphere_guest:
    vcenter_hostname: "{{ mgmt_vc }}"
    username: "{{ mgmt_vc_username }}"
    password: "{{ mgmt_vc_password }}"
    guest: "{{ vra_name }}"
    state: absent
    force: yes
  register: vra_deleted
